root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
pre_cmd = []
cmd = "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig go build -ldflags '-s -w' -o tmp/main cmd/main.go"
post_cmd = []
bin = "tmp/main"
full_bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
include_dir = ["cmd", "internal", "pkg", "migrations"]
exclude_dir = ["assets", "tmp", "vendor", "internal/static/dist", "build", "web", "uploads", "node_modules", ".git", "docs", "scripts"]
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
poll = false
poll_interval = 500
rerun = false
rerun_delay = 500
stop_on_root = false
log = false
delay = 1000
send_interrupt = true
kill_delay = 1000

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
